// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwvYhAJ_TaEsPzlRAppxXr1V9bpl71uSA',
    appId: '1:649073849469:web:c088a5a2d6d11f6296ad14',
    messagingSenderId: '649073849469',
    projectId: 'superepicgrocerylist',
    authDomain: 'superepicgrocerylist.firebaseapp.com',
    storageBucket: 'superepicgrocerylist.firebasestorage.app',
    measurementId: 'G-3ZNVLG56MW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChiH4D2WcTy8iBontYTvCW0nnLifTvKsk',
    appId: '1:649073849469:android:e0511c69f7cf408d96ad14',
    messagingSenderId: '649073849469',
    projectId: 'superepicgrocerylist',
    storageBucket: 'superepicgrocerylist.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHCLHO2p9o9ejIyf44pTWAYrXX5NXYkos',
    appId: '1:649073849469:ios:b93e2b776d10037896ad14',
    messagingSenderId: '649073849469',
    projectId: 'superepicgrocerylist',
    storageBucket: 'superepicgrocerylist.firebasestorage.app',
    iosBundleId: 'com.example.superepicgrocerylist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHCLHO2p9o9ejIyf44pTWAYrXX5NXYkos',
    appId: '1:649073849469:ios:b93e2b776d10037896ad14',
    messagingSenderId: '649073849469',
    projectId: 'superepicgrocerylist',
    storageBucket: 'superepicgrocerylist.firebasestorage.app',
    iosBundleId: 'com.example.superepicgrocerylist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwvYhAJ_TaEsPzlRAppxXr1V9bpl71uSA',
    appId: '1:649073849469:web:f01373beca3af40f96ad14',
    messagingSenderId: '649073849469',
    projectId: 'superepicgrocerylist',
    authDomain: 'superepicgrocerylist.firebaseapp.com',
    storageBucket: 'superepicgrocerylist.firebasestorage.app',
    measurementId: 'G-5BD7KFF4FE',
  );
}
